// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYHm-dgDZ1iORNgo5ukQJlXDkgaKeLHEI',
    appId: '1:1073291011558:web:1ad943d8e9c8be63836227',
    messagingSenderId: '1073291011558',
    projectId: 'guia-del-norte-fbd7b',
    authDomain: 'guia-del-norte-fbd7b.firebaseapp.com',
    storageBucket: 'guia-del-norte-fbd7b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9n0SPB7k5Z9STnmrg5rpiwXB2hyGrdeE',
    appId: '1:1073291011558:android:5c1ea9208d523006836227',
    messagingSenderId: '1073291011558',
    projectId: 'guia-del-norte-fbd7b',
    storageBucket: 'guia-del-norte-fbd7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDULLKAd1ByT92EhUay0HGbTywVFxEH8Vw',
    appId: '1:1073291011558:ios:3a7ea93258d0d95a836227',
    messagingSenderId: '1073291011558',
    projectId: 'guia-del-norte-fbd7b',
    storageBucket: 'guia-del-norte-fbd7b.firebasestorage.app',
    iosClientId: '1073291011558-07oh735fpe4rmgthfp3otbk60k4hhrml.apps.googleusercontent.com',
    iosBundleId: 'com.example.guiaDelNorte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDULLKAd1ByT92EhUay0HGbTywVFxEH8Vw',
    appId: '1:1073291011558:ios:3a7ea93258d0d95a836227',
    messagingSenderId: '1073291011558',
    projectId: 'guia-del-norte-fbd7b',
    storageBucket: 'guia-del-norte-fbd7b.firebasestorage.app',
    iosClientId: '1073291011558-07oh735fpe4rmgthfp3otbk60k4hhrml.apps.googleusercontent.com',
    iosBundleId: 'com.example.guiaDelNorte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYHm-dgDZ1iORNgo5ukQJlXDkgaKeLHEI',
    appId: '1:1073291011558:web:ce47316f8ce4258d836227',
    messagingSenderId: '1073291011558',
    projectId: 'guia-del-norte-fbd7b',
    authDomain: 'guia-del-norte-fbd7b.firebaseapp.com',
    storageBucket: 'guia-del-norte-fbd7b.firebasestorage.app',
  );
}
